// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX34RwWO9mLr3o3q4MOwH3V5NkXPvYY7Y',
    appId: '1:136001590052:web:70c3c31a8fbc453f6059b1',
    messagingSenderId: '136001590052',
    projectId: 'car-wash-lighting',
    authDomain: 'car-wash-lighting.firebaseapp.com',
    databaseURL: 'https://car-wash-lighting-default-rtdb.firebaseio.com',
    storageBucket: 'car-wash-lighting.appspot.com',
    measurementId: 'G-V2176V3F4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkztrkwlaU170TBgx33Jm5-soTOyTOusg',
    appId: '1:136001590052:android:50064ab9ddbf796d6059b1',
    messagingSenderId: '136001590052',
    projectId: 'car-wash-lighting',
    databaseURL: 'https://car-wash-lighting-default-rtdb.firebaseio.com',
    storageBucket: 'car-wash-lighting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT1RFXpLSno3XVLlc2QW3F-qjhblkl_eA',
    appId: '1:136001590052:ios:a7595ae1398448506059b1',
    messagingSenderId: '136001590052',
    projectId: 'car-wash-lighting',
    databaseURL: 'https://car-wash-lighting-default-rtdb.firebaseio.com',
    storageBucket: 'car-wash-lighting.appspot.com',
    androidClientId: '136001590052-ckturnc7ks5npj61ums0o2gkdom2kaqa.apps.googleusercontent.com',
    iosClientId: '136001590052-rjpgfmha94nudh8iflblrjtf5q2l0eq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.carwashAdmin',
  );
}
